// Code generated by generator, DO NOT EDIT.
package generate

import (
	"context"
	model "github.com/mercadolibre/fury_payment-methods-write-v2/src/api/internal/model"
	p "p"
	"time"
)

type PaymentMethodTypeChangeSet struct {
	ID        *int64
	Name      *string
	Code      *string
	CreatedAt *time.Time
	CreatedBy *string
	UpdatedAt *time.Time
	UpdatedBy *string
}

func (c PaymentMethodTypeChangeSet) toMap() map[string]interface{} {
	m := make(map[string]interface{})
	return m
}
func (c PaymentMethodTypeDAO) Get(ctx context.Context, id int) (model.PaymentMethodType, error) {
	var query = "SELECT id, name, code, created_at, created_by, updated_at, updated_by FROM PaymentMethodType WHERE id = ?"

	var row model.PaymentMethodType

	err := p.db.Get(&row, query, id)

	if err != nil {
		return model.PaymentMethodType{}, err
	}

	return row, nil
}
